const PATTERN_DIGIT = "\\d";
const PATTERN_ALPHANUMERIC = "\\w";
const PATTERN_GROUP = "[";
const PATTERN_GROUP_CLOSE = "]";
const PATTERN_ANCHOR_FRONT = "^";
const PATTERN_ANCHOR_BACK = "$";
const PATTERN_REPEAT = "+";
const PATTERN_ZERO_OR_MORE = "?";
const PATTERN_WILDCARD = ".";
const PATTERN_OR_OPEN = "(";
const PATTERN_OR_CLOSE = ")";
const PATTERN_OR = "|";

const ALPHANUMERIC_RANGES = {
  digitStrings: [48, 57],
  alphaLower: [97, 122],
  alphaUpper: [65, 90],
  underscore: [95, 95],
};

module.exports = {
  PATTERN_DIGIT,
  PATTERN_ALPHANUMERIC,
  PATTERN_GROUP,
  PATTERN_GROUP_CLOSE,
  PATTERN_REPEAT,
  PATTERN_WILDCARD,
  PATTERN_ZERO_OR_MORE,
  PATTERN_ANCHOR_FRONT,
  PATTERN_ANCHOR_BACK,
  PATTERN_OR_OPEN,
  PATTERN_OR_CLOSE,
  PATTERN_OR,
  ALPHANUMERIC_RANGES,
};
